version: "2"

services:
  cflskapp:
    image: artsh8/flskap
    ports:
      - 5000:5000
    depends_on:
      - cclick
      - kafka
    environment:
      - CLICK_HOST=10.5.0.5
      - KAFKA_BOOTSTRAP_SERVERS=10.5.0.6:9092
    networks:
      flsk-network:
        ipv4_address: 10.5.0.2
  
  cflsk-generator0:
    image: artsh8/flsk-generator
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=10.5.0.6:9092
      - KAFKA_PARTITION=0
      - SCY_HOST=10.5.0.7
    tty: true
    stdin_open: true
    depends_on:
    - carchive-server
    networks:
      flsk-network:
        ipv4_address: 10.5.0.3

  cflsk-generator1:
    image: artsh8/flsk-generator
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=10.5.0.6:9092
      - KAFKA_PARTITION=1
      - SCY_HOST=10.5.0.7
    tty: true
    stdin_open: true
    depends_on:
    - carchive-server
    networks:
      flsk-network:
        ipv4_address: 10.5.0.4

  carchive-server:
    image: artsh8/flsk-archive-server
    environment:
      - SCY_HOST=10.5.0.7
      - GRPC_PORT=10.5.0.8:50051
    tty: true
    stdin_open: true
    depends_on:
      - cscylla
    networks:
      flsk-network:
        ipv4_address: 10.5.0.8
    
  carchive-client:
    image: artsh8/flsk-archive-client
    environment:
      - CLICK_HOST=10.5.0.5
      - KAFKA_BOOTSTRAP_SERVERS=10.5.0.6:9092
      - GRPC_PORT=10.5.0.8:50051
    tty: true
    stdin_open: true
    depends_on:
      - cclick
      - kafka
      - carchive-server
    networks:
      flsk-network:
        ipv4_address: 10.5.0.9

  cclick:
    image: clickhouse/clickhouse-server
    environment:
      - CLICKHOUSE_USER=username
      - CLICKHOUSE_PASSWORD=password
    networks:
      flsk-network:
        ipv4_address: 10.5.0.5
  
  cscylla:
    image: scylladb/scylla
    command: --smp=1
    networks:
      flsk-network:
        ipv4_address: 10.5.0.7

  kafka:
    image: docker.io/bitnami/kafka:3.6
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    networks:
      flsk-network:
        ipv4_address: 10.5.0.6

networks:
  flsk-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
