# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: archive.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rarchive.proto\x12\x07\x61rchive\"(\n\x0e\x41rchiveRequest\x12\x16\n\x0erequest_string\x18\x01 \x01(\t\"\xa5\x01\n\x0fTransactionInfo\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x13\n\x0b\x63ustomer_id\x18\x03 \x01(\r\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x01\x12\x32\n\x10transaction_type\x18\x05 \x01(\x0e\x32\x18.archive.TransactionType\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\"B\n\x0c\x41rchiveReply\x12\x32\n\x10transaction_info\x18\x01 \x03(\x0b\x32\x18.archive.TransactionInfo\"J\n\nAckRequest\x12\x16\n\x0erequest_string\x18\x01 \x01(\t\x12\x0c\n\x04year\x18\x02 \x01(\r\x12\x16\n\x0etransaction_id\x18\x03 \x03(\t\"\x19\n\x08\x41\x63kReply\x12\r\n\x05reply\x18\x01 \x01(\t*6\n\x0fTransactionType\x12\n\n\x06\x43REDIT\x10\x00\x12\t\n\x05\x44\x45\x42IT\x10\x01\x12\x0c\n\x08TRANSFER\x10\x02\x32t\n\x08\x41rchiver\x12\x39\n\x07\x41rchive\x12\x17.archive.ArchiveRequest\x1a\x15.archive.ArchiveReply\x12-\n\x03\x41\x63k\x12\x13.archive.AckRequest\x1a\x11.archive.AckReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'archive_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TRANSACTIONTYPE']._serialized_start=407
  _globals['_TRANSACTIONTYPE']._serialized_end=461
  _globals['_ARCHIVEREQUEST']._serialized_start=26
  _globals['_ARCHIVEREQUEST']._serialized_end=66
  _globals['_TRANSACTIONINFO']._serialized_start=69
  _globals['_TRANSACTIONINFO']._serialized_end=234
  _globals['_ARCHIVEREPLY']._serialized_start=236
  _globals['_ARCHIVEREPLY']._serialized_end=302
  _globals['_ACKREQUEST']._serialized_start=304
  _globals['_ACKREQUEST']._serialized_end=378
  _globals['_ACKREPLY']._serialized_start=380
  _globals['_ACKREPLY']._serialized_end=405
  _globals['_ARCHIVER']._serialized_start=463
  _globals['_ARCHIVER']._serialized_end=579
# @@protoc_insertion_point(module_scope)
